"use client";

import { jsPDF } from "jspdf";

import { drawClientPdfHeaderSync } from "@/lib/brand/pdf-header";
import { Button } from "@/components/ui/button";
import {
  MEETING_TYPE_LABELS,
  type Meeting,
  type MeetingAction,
} from "@/lib/types/meetings";

export function MeetingExportButton({
  meeting,
  actions,
  brandName,
  primaryColor,
}: {
  meeting: Meeting;
  actions: MeetingAction[];
  brandName: string;
  primaryColor?: string | null;
}) {
  function exportPdf() {
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const primary = primaryColor ?? "#0F6F68";
    let y = drawClientPdfHeaderSync(doc, {
      brandName,
      primaryColor: primary,
      subtitle: MEETING_TYPE_LABELS[meeting.type] ?? "Meeting",
    });

    const write = (text: string, size = 11, bold = false) => {
      doc.setFontSize(size);
      doc.setFont("helvetica", bold ? "bold" : "normal");
      doc.setTextColor(bold && size >= 14 ? primary : "#1A2422");
      const lines = doc.splitTextToSize(text, 500);
      for (const line of lines) {
        if (y > 780) {
          doc.addPage();
          y = 48;
        }
        doc.text(line, 48, y);
        y += size + 3;
      }
    };

    write(meeting.title, 18, true);
    write(
      `${new Date(meeting.scheduled_for).toLocaleString()} · ${meeting.status}`,
      10,
    );
    y += 8;
    if (meeting.executive_summary) {
      write("Summary", 14, true);
      write(meeting.executive_summary);
      y += 6;
    }
    if (meeting.minutes_markdown) {
      write("Minutes", 14, true);
      write(meeting.minutes_markdown.replace(/[#*_`]/g, ""));
      y += 6;
    }
    if ((meeting.decisions ?? []).length) {
      write("Decisions", 14, true);
      for (const d of meeting.decisions ?? []) {
        write(`• ${d.title}${d.rationale ? ` — ${d.rationale}` : ""}`);
      }
      y += 6;
    }
    if (actions.length) {
      write("Actions", 14, true);
      for (const a of actions) {
        write(`• [${a.status}] ${a.description}`);
      }
    }
    y += 12;
    doc.setFontSize(9);
    doc.setTextColor("#5A6E6B");
    doc.text("Generated by Simba AI", 48, y);

    doc.save(
      `${meeting.title.replace(/\s+/g, "-").toLowerCase()}-minutes.pdf`,
    );
  }

  return (
    <Button type="button" variant="outline" size="sm" onClick={exportPdf}>
      Export PDF
    </Button>
  );
}
