"use client";

import { useActionState } from "react";
import { jsPDF } from "jspdf";

import { drawClientPdfHeaderSync } from "@/lib/brand/pdf-header";
import {
  pushInsightsToBrand,
  refreshResearch,
  type ResearchActionResult,
} from "@/lib/research/actions";
import type { ResearchDocument, ResearchProject } from "@/lib/types/research";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

const initial: ResearchActionResult = {};

export function ResearchActions({
  project,
  documents,
  canWrite,
  brandName,
  primaryColor,
}: {
  project: ResearchProject;
  documents: ResearchDocument[];
  canWrite: boolean;
  brandName?: string;
  primaryColor?: string | null;
}) {
  const [pushState, pushAction, pushPending] = useActionState(
    pushInsightsToBrand,
    initial,
  );
  const [refreshState, refreshAction, refreshPending] = useActionState(
    refreshResearch,
    initial,
  );

  function exportPdf() {
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const primary = primaryColor ?? "#0F6F68";
    let y = drawClientPdfHeaderSync(doc, {
      brandName: brandName ?? "Research",
      primaryColor: primary,
      subtitle: "Research report",
    });
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(primary);
    doc.text(project.title, 48, y);
    y += 22;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor("#1A2422");
    for (const section of documents) {
      if (y > 740) {
        doc.addPage();
        y = 48;
      }
      doc.setFont("helvetica", "bold");
      doc.setTextColor(primary);
      doc.text(section.section.replaceAll("_", " "), 48, y);
      y += 16;
      doc.setFont("helvetica", "normal");
      doc.setTextColor("#1A2422");
      const lines = doc.splitTextToSize(
        section.content.replace(/[#*_`]/g, ""),
        500,
      );
      for (const line of lines) {
        if (y > 780) {
          doc.addPage();
          y = 48;
        }
        doc.text(line, 48, y);
        y += 14;
      }
      y += 10;
    }
    y += 8;
    doc.setFontSize(9);
    doc.setTextColor("#5A6E6B");
    doc.text("Generated by Simba AI", 48, y);
    doc.save(`${project.title.replace(/\s+/g, "-").toLowerCase()}.pdf`);
  }

  const feedback = pushState.error || pushState.success || refreshState.error;

  return (
    <div className="space-y-4 rounded-lg bg-card p-5 shadow-elevated ring-1 ring-border">
      <div className="flex flex-wrap gap-2">
        <Button type="button" variant="outline" onClick={exportPdf}>
          Export PDF
        </Button>
        {canWrite && project.status === "complete" ? (
          <form action={pushAction}>
            <input type="hidden" name="projectId" value={project.id} />
            <Button type="submit" disabled={pushPending}>
              {pushPending ? "Pushing…" : "Push insights to Brand profile"}
            </Button>
          </form>
        ) : null}
      </div>

      {canWrite ? (
        <form action={refreshAction} className="space-y-3 border-t border-border pt-4">
          <input type="hidden" name="projectId" value={project.id} />
          <p className="text-sm font-medium text-ink">Refresh research</p>
          <p className="text-xs text-ink-soft">
            Re-runs the agent with this report as prior context.
          </p>
          <Textarea
            name="notes"
            rows={3}
            placeholder="Optional refresh brief (what changed?)"
          />
          <Button type="submit" variant="secondary" disabled={refreshPending}>
            {refreshPending ? "Queuing refresh…" : "Refresh"}
          </Button>
        </form>
      ) : null}

      {feedback ? (
        <Alert
          variant={
            pushState.error || refreshState.error ? "destructive" : "default"
          }
        >
          <AlertDescription>{feedback}</AlertDescription>
        </Alert>
      ) : null}
    </div>
  );
}
