import { jsPDF } from "jspdf";

import {
  SIMBA_THEME_FALLBACK,
  normalizeHex,
} from "@/lib/brand/theme";

export type PdfBrandHeader = {
  brandName: string;
  primaryColor?: string | null;
  logoUrl?: string | null;
  subtitle?: string;
};

async function fetchImageDataUrl(url: string): Promise<string | null> {
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(8000) });
    if (!res.ok) return null;
    const buf = Buffer.from(await res.arrayBuffer());
    const ctype = res.headers.get("content-type") ?? "image/png";
    const mime = ctype.includes("jpeg") || ctype.includes("jpg")
      ? "image/jpeg"
      : ctype.includes("webp")
        ? "image/webp"
        : "image/png";
    return `data:${mime};base64,${buf.toString("base64")}`;
  } catch {
    return null;
  }
}

/**
 * Draw a client-branded header bar on the first page of a jsPDF document.
 * Returns the Y position below the header for content start.
 */
export async function drawClientPdfHeader(
  doc: jsPDF,
  branding: PdfBrandHeader,
): Promise<number> {
  const primary =
    normalizeHex(branding.primaryColor) ?? SIMBA_THEME_FALLBACK.primaryColor;
  const margin = 48;
  const barH = branding.logoUrl ? 52 : 36;

  doc.setFillColor(primary);
  doc.rect(0, 0, 595, barH, "F");

  let textX = margin;
  if (branding.logoUrl) {
    const dataUrl = await fetchImageDataUrl(branding.logoUrl);
    if (dataUrl) {
      try {
        const format = dataUrl.includes("image/jpeg") ? "JPEG" : "PNG";
        doc.addImage(dataUrl, format, margin, 10, 28, 28);
        textX = margin + 36;
      } catch {
        // Logo decode failed — continue with text-only header
      }
    }
  }

  doc.setTextColor("#ffffff");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  const title = branding.subtitle
    ? `${branding.brandName} · ${branding.subtitle}`
    : branding.brandName;
  doc.text(title, textX, branding.logoUrl ? 28 : 22);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor("#ffffff");
  doc.text("Generated by Simba AI", 595 - margin, branding.logoUrl ? 28 : 22, {
    align: "right",
  });

  return barH + 20;
}

/** Sync header for client-side jsPDF (no logo fetch — colors + name only). */
export function drawClientPdfHeaderSync(
  doc: jsPDF,
  branding: PdfBrandHeader,
): number {
  const primary =
    normalizeHex(branding.primaryColor) ?? SIMBA_THEME_FALLBACK.primaryColor;
  const margin = 48;
  doc.setFillColor(primary);
  doc.rect(0, 0, 595, 36, "F");
  doc.setTextColor("#ffffff");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  const title = branding.subtitle
    ? `${branding.brandName} · ${branding.subtitle}`
    : branding.brandName;
  doc.text(title, margin, 22);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Generated by Simba AI", 595 - margin, 22, { align: "right" });
  return 56;
}
