/**
 * Code-level registry of every real runnable agent / Inngest job.
 * Do not pad with fictional agents — every entry maps to an execution path.
 */

export const AGENT_DEPARTMENTS = [
  "executive",
  "research",
  "strategy",
  "content",
  "social",
  "advertising",
  "seo",
  "email",
  "crm",
  "finance",
  "analytics",
  "compliance",
  "operations",
] as const;

export type AgentDepartment = (typeof AGENT_DEPARTMENTS)[number];

export const DEPARTMENT_META: Record<
  AgentDepartment,
  { label: string; blurb: string; href: string }
> = {
  executive: {
    label: "Executive",
    blurb: "CEO accountability, standups, board packs, and performance reviews",
    href: "/meetings",
  },
  research: {
    label: "Research",
    blurb: "Brand, competitor, market, and audience intelligence",
    href: "/research",
  },
  strategy: {
    label: "Strategy & Planning",
    blurb: "Marketing plans, campaign tasks, and execution",
    href: "/planning",
  },
  content: {
    label: "Content",
    blurb: "Posts, batches, scripts, repurpose, and growth reviews",
    href: "/content",
  },
  social: {
    label: "Social",
    blurb: "Publishing pipeline and organic metrics",
    href: "/social",
  },
  advertising: {
    label: "Advertising",
    blurb: "Media plans, creative, metrics, and optimisation",
    href: "/ads",
  },
  seo: {
    label: "SEO",
    blurb: "Keywords, briefs, articles, GSC, and technical audits",
    href: "/seo",
  },
  email: {
    label: "Email",
    blurb: "Campaigns, flows, and scheduled sends",
    href: "/email",
  },
  crm: {
    label: "CRM",
    blurb: "Pipeline reviews, scoring, and follow-ups",
    href: "/crm",
  },
  finance: {
    label: "Finance",
    blurb: "Spend ingestion and weekly analyst briefs",
    href: "/finance",
  },
  analytics: {
    label: "Data & Analytics",
    blurb: "GA4 rollups, anomalies, and metric Q&A",
    href: "/data",
  },
  compliance: {
    label: "Compliance",
    blurb: "Content checks and data-deletion processing",
    href: "/compliance",
  },
  operations: {
    label: "Operations",
    blurb: "Integrations, automations, digests, and job recovery",
    href: "/team",
  },
};

export type AgentTrigger =
  | { kind: "cron"; schedule: string }
  | { kind: "event"; event: string }
  | { kind: "on_demand" };

export type AgentRunNowKind =
  | "meeting"
  | "report"
  | "ads_optimisation"
  | "ads_sync_metrics"
  | "organic_growth"
  | "content_cadence_fill"
  | "ceo_check"
  | "ads_budget_loop"
  | "finance_ingest"
  | "finance_analyst"
  | "pipeline_review"
  | "analytics_rollup"
  | "seo_weekly_summary";

export type AgentRegistryEntry = {
  /** Stable UI / routing id */
  id: string;
  displayName: string;
  roleTitle: string;
  department: AgentDepartment;
  responsibility: string;
  trigger: AgentTrigger;
  /** Dashboard module key */
  module: string;
  /** Primary code path that executes this agent */
  executionPath: string;
  /** Inngest function id when scheduled/event-driven */
  inngestId?: string;
  /**
   * Values written to agent_runs.agent_name for this agent.
   * Empty when the job does not yet persist runs (still a real executor).
   */
  agentNames: string[];
  /** Show Run now when defined; handler in lib/team/run-actions.ts */
  runNow?: {
    kind: AgentRunNowKind;
    requiresBrand?: boolean;
    /** Meeting / report type payload */
    type?: string;
  };
  /** Default deep link when a run has no entity id */
  moduleHref: string;
};

export const AGENT_REGISTRY: AgentRegistryEntry[] = [
  // ── Executive ────────────────────────────────────────────────────────────
  {
    id: "chief-executive",
    displayName: "Chief Executive",
    roleTitle: "CEO / Accountability",
    department: "executive",
    responsibility:
      "Deterministic department health checks, remediations, hiring proposals, and standup accountability — before the daily standup.",
    trigger: { kind: "cron", schedule: "45 6 * * *" },
    module: "meetings",
    executionPath: "lib/ceo/run.ts",
    inngestId: "ceo/daily-check",
    agentNames: ["chief_executive"],
    runNow: { kind: "ceo_check", requiresBrand: true },
    moduleHref: "/meetings",
  },
  {
    id: "daily-standup",
    displayName: "Daily Standup Lead",
    roleTitle: "Standup Facilitator",
    department: "executive",
    responsibility:
      "Runs the daily standup: blockers, priorities, and typed follow-up actions.",
    trigger: { kind: "cron", schedule: "5 * * * *" },
    module: "meetings",
    executionPath: "lib/meetings/run.ts",
    inngestId: "meetings/run",
    agentNames: ["daily_standup"],
    runNow: { kind: "meeting", requiresBrand: true, type: "daily_standup" },
    moduleHref: "/meetings",
  },
  {
    id: "weekly-marketing",
    displayName: "Weekly Marketing Chair",
    roleTitle: "Weekly Panel Lead",
    department: "executive",
    responsibility:
      "Hosts the weekly marketing panel with KPI context and action items.",
    trigger: { kind: "cron", schedule: "5 * * * *" },
    module: "meetings",
    executionPath: "lib/meetings/run.ts",
    inngestId: "meetings/run",
    agentNames: ["weekly_marketing"],
    runNow: { kind: "meeting", requiresBrand: true, type: "weekly_marketing" },
    moduleHref: "/meetings",
  },
  {
    id: "monthly-board",
    displayName: "Monthly Board Secretary",
    roleTitle: "Board Pack Author",
    department: "executive",
    responsibility: "Produces monthly board packs with performance narrative.",
    trigger: { kind: "cron", schedule: "5 * * * *" },
    module: "meetings",
    executionPath: "lib/meetings/run.ts",
    inngestId: "meetings/run",
    agentNames: ["monthly_board"],
    runNow: { kind: "meeting", requiresBrand: true, type: "monthly_board" },
    moduleHref: "/meetings",
  },
  {
    id: "quarterly-board",
    displayName: "Quarterly Board Secretary",
    roleTitle: "Quarterly Review Lead",
    department: "executive",
    responsibility: "Runs quarterly board reviews against strategic goals.",
    trigger: { kind: "cron", schedule: "5 * * * *" },
    module: "meetings",
    executionPath: "lib/meetings/run.ts",
    inngestId: "meetings/run",
    agentNames: ["quarterly_board"],
    runNow: { kind: "meeting", requiresBrand: true, type: "quarterly_board" },
    moduleHref: "/meetings",
  },
  {
    id: "annual-review",
    displayName: "Annual Review Lead",
    roleTitle: "Annual Strategist",
    department: "executive",
    responsibility: "Compiles the annual marketing review and forward plan.",
    trigger: { kind: "cron", schedule: "5 * * * *" },
    module: "meetings",
    executionPath: "lib/meetings/run.ts",
    inngestId: "meetings/run",
    agentNames: ["annual_review"],
    runNow: { kind: "meeting", requiresBrand: true, type: "annual_review" },
    moduleHref: "/meetings",
  },
  {
    id: "meetings-scheduler",
    displayName: "Meeting Scheduler",
    roleTitle: "Executive Ops",
    department: "executive",
    responsibility:
      "Hourly cron that queues due standups, panels, and board meetings.",
    trigger: { kind: "cron", schedule: "5 * * * *" },
    module: "meetings",
    executionPath: "lib/inngest/functions/meetings.ts",
    inngestId: "meetings/hourly-scheduler",
    agentNames: [],
    moduleHref: "/meetings/settings",
  },
  {
    id: "report-daily",
    displayName: "Daily Performance Analyst",
    roleTitle: "Daily Reporter",
    department: "executive",
    responsibility: "Generates daily performance reports for the brand.",
    trigger: { kind: "cron", schedule: "10 * * * *" },
    module: "reviews",
    executionPath: "lib/reviews/run.ts",
    inngestId: "reviews/run",
    agentNames: ["report_daily"],
    runNow: { kind: "report", requiresBrand: true, type: "daily" },
    moduleHref: "/reviews",
  },
  {
    id: "report-weekly",
    displayName: "Weekly Performance Analyst",
    roleTitle: "Weekly Reporter",
    department: "executive",
    responsibility: "Generates weekly performance reports with period deltas.",
    trigger: { kind: "cron", schedule: "10 * * * *" },
    module: "reviews",
    executionPath: "lib/reviews/run.ts",
    inngestId: "reviews/run",
    agentNames: ["report_weekly"],
    runNow: { kind: "report", requiresBrand: true, type: "weekly" },
    moduleHref: "/reviews",
  },
  {
    id: "report-monthly",
    displayName: "Monthly Performance Analyst",
    roleTitle: "Monthly Reporter",
    department: "executive",
    responsibility: "Produces monthly review packs from live KPI rollups.",
    trigger: { kind: "cron", schedule: "10 * * * *" },
    module: "reviews",
    executionPath: "lib/reviews/run.ts",
    inngestId: "reviews/run",
    agentNames: ["report_monthly"],
    runNow: { kind: "report", requiresBrand: true, type: "monthly" },
    moduleHref: "/reviews",
  },
  {
    id: "report-quarterly",
    displayName: "Quarterly Performance Analyst",
    roleTitle: "Quarterly Reporter",
    department: "executive",
    responsibility: "Produces quarterly performance narratives.",
    trigger: { kind: "cron", schedule: "10 * * * *" },
    module: "reviews",
    executionPath: "lib/reviews/run.ts",
    inngestId: "reviews/run",
    agentNames: ["report_quarterly"],
    runNow: { kind: "report", requiresBrand: true, type: "quarterly" },
    moduleHref: "/reviews",
  },
  {
    id: "reviews-scheduler",
    displayName: "Report Scheduler",
    roleTitle: "Reviews Ops",
    department: "executive",
    responsibility: "Hourly cron that queues due performance reports.",
    trigger: { kind: "cron", schedule: "10 * * * *" },
    module: "reviews",
    executionPath: "lib/inngest/functions/reviews.ts",
    inngestId: "reviews/hourly-scheduler",
    agentNames: [],
    moduleHref: "/reviews/settings",
  },

  // ── Research ─────────────────────────────────────────────────────────────
  {
    id: "research-brand-audit",
    displayName: "Brand Auditor",
    roleTitle: "Brand Research Analyst",
    department: "research",
    responsibility: "Deep brand audit from brief, site, and competitive context.",
    trigger: { kind: "event", event: "research/run.requested" },
    module: "research",
    executionPath: "lib/agents/research/runner.ts",
    inngestId: "research/run-project",
    agentNames: ["brand_audit"],
    moduleHref: "/research",
  },
  {
    id: "research-competitor",
    displayName: "Competitor Analyst",
    roleTitle: "Competitive Intelligence",
    department: "research",
    responsibility: "Profiles competitors and builds comparison matrices.",
    trigger: { kind: "event", event: "research/run.requested" },
    module: "research",
    executionPath: "lib/agents/research/runner.ts",
    inngestId: "research/run-project",
    agentNames: ["competitor"],
    moduleHref: "/research",
  },
  {
    id: "research-market",
    displayName: "Market Analyst",
    roleTitle: "Market Research",
    department: "research",
    responsibility: "Maps market structure, size signals, and opportunity.",
    trigger: { kind: "event", event: "research/run.requested" },
    module: "research",
    executionPath: "lib/agents/research/runner.ts",
    inngestId: "research/run-project",
    agentNames: ["market"],
    moduleHref: "/research",
  },
  {
    id: "research-keyword",
    displayName: "Keyword Researcher",
    roleTitle: "Keyword Research",
    department: "research",
    responsibility: "Discovers keyword themes and search intent clusters.",
    trigger: { kind: "event", event: "research/run.requested" },
    module: "research",
    executionPath: "lib/agents/research/runner.ts",
    inngestId: "research/run-project",
    agentNames: ["keyword"],
    moduleHref: "/research",
  },
  {
    id: "research-audience",
    displayName: "Audience Researcher",
    roleTitle: "Audience Insights",
    department: "research",
    responsibility: "Builds audience segments, jobs-to-be-done, and messaging.",
    trigger: { kind: "event", event: "research/run.requested" },
    module: "research",
    executionPath: "lib/agents/research/runner.ts",
    inngestId: "research/run-project",
    agentNames: ["audience"],
    moduleHref: "/research",
  },
  {
    id: "research-trend",
    displayName: "Trend Spotter",
    roleTitle: "Trend Research",
    department: "research",
    responsibility: "Surfaces category trends relevant to the brand.",
    trigger: { kind: "event", event: "research/run.requested" },
    module: "research",
    executionPath: "lib/agents/research/runner.ts",
    inngestId: "research/run-project",
    agentNames: ["trend"],
    moduleHref: "/research",
  },
  {
    id: "brand-extraction",
    displayName: "Brand Identity Extractor",
    roleTitle: "Brand Identity Analyst",
    department: "research",
    responsibility: "Extracts brand identity from a website URL via Claude.",
    trigger: { kind: "on_demand" },
    module: "brand",
    executionPath: "lib/brand/extract.ts",
    agentNames: ["brand_extraction"],
    moduleHref: "/brand/setup",
  },
  {
    id: "brand-guidelines-pdf",
    displayName: "Guidelines Ingestor",
    roleTitle: "Brand Guidelines Analyst",
    department: "research",
    responsibility: "Ingests PDF brand guidelines into structured proposals.",
    trigger: { kind: "event", event: "brand/guidelines.pdf.ingest" },
    module: "brand",
    executionPath: "lib/media/guidelines-ingest.ts",
    inngestId: "brand/guidelines-pdf-ingest",
    agentNames: ["brand_guidelines_pdf"],
    moduleHref: "/brand/guidelines",
  },

  // ── Strategy & Planning ──────────────────────────────────────────────────
  {
    id: "marketing-planner",
    displayName: "Marketing Planner",
    roleTitle: "Strategy Lead",
    department: "strategy",
    responsibility: "Drafts multi-section marketing plans for human approval.",
    trigger: { kind: "on_demand" },
    module: "planning",
    executionPath: "lib/planning/actions.ts",
    agentNames: ["marketing_planner"],
    moduleHref: "/planning",
  },
  {
    id: "planning-daily-execution",
    displayName: "Plan Executor",
    roleTitle: "Campaign Ops",
    department: "strategy",
    responsibility:
      "Daily cron that runs due AI plan tasks and refreshes campaign KPIs.",
    trigger: { kind: "cron", schedule: "0 6 * * *" },
    module: "planning",
    executionPath: "lib/planning/execution.ts",
    inngestId: "planning/daily-execution",
    agentNames: ["content_single_post"],
    moduleHref: "/planning",
  },
  {
    id: "planning-execute-task",
    displayName: "Task Runner",
    roleTitle: "AI Task Executor",
    department: "strategy",
    responsibility: "Executes a single campaign AI task on demand.",
    trigger: { kind: "event", event: "planning/task.execute" },
    module: "planning",
    executionPath: "lib/planning/execution.ts",
    inngestId: "planning/execute-task-now",
    agentNames: ["content_single_post"],
    moduleHref: "/planning",
  },

  // ── Content ──────────────────────────────────────────────────────────────
  {
    id: "content-single",
    displayName: "Post Writer",
    roleTitle: "Content Creator",
    department: "content",
    responsibility: "Generates a single social post or script with compliance.",
    trigger: { kind: "event", event: "content/generate.single" },
    module: "content",
    executionPath: "lib/inngest/functions/content.ts",
    inngestId: "content/generate-single",
    agentNames: ["content_single_post"],
    moduleHref: "/content/generate",
  },
  {
    id: "content-batch-plan",
    displayName: "Batch Planner",
    roleTitle: "Editorial Planner",
    department: "content",
    responsibility: "Proposes a multi-slot content plan for a date range.",
    trigger: { kind: "event", event: "content/generate.batch-propose" },
    module: "content",
    executionPath: "lib/inngest/functions/content.ts",
    inngestId: "content/batch-propose",
    agentNames: ["content_batch_plan"],
    moduleHref: "/content",
  },
  {
    id: "content-batch-generate",
    displayName: "Batch Producer",
    roleTitle: "Content Producer",
    department: "content",
    responsibility: "Generates approved plan slots into content items.",
    trigger: { kind: "event", event: "content/generate.batch-slots" },
    module: "content",
    executionPath: "lib/inngest/functions/content.ts",
    inngestId: "content/batch-generate-slots",
    agentNames: ["content_batch_generate"],
    moduleHref: "/content/queue",
  },
  {
    id: "content-repurpose",
    displayName: "Repurposer",
    roleTitle: "Cross-Platform Adapter",
    department: "content",
    responsibility: "Adapts a source piece across platforms and formats.",
    trigger: { kind: "event", event: "content/generate.repurpose" },
    module: "content",
    executionPath: "lib/inngest/functions/content.ts",
    inngestId: "content/repurpose",
    agentNames: ["content_repurpose"],
    moduleHref: "/content",
  },
  {
    id: "content-cadence-fill",
    displayName: "Cadence Filler",
    roleTitle: "Organic Engine",
    department: "content",
    responsibility:
      "Keeps the next 7 days of organic slots filled to brand cadence (feed + Instagram stories).",
    trigger: { kind: "cron", schedule: "30 5 * * *" },
    module: "content",
    executionPath: "lib/content/cadence-fill.ts",
    inngestId: "content/daily-cadence-fill",
    agentNames: ["content_cadence_fill"],
    runNow: { kind: "content_cadence_fill", requiresBrand: false },
    moduleHref: "/content/calendar",
  },
  {
    id: "organic-growth",
    displayName: "Organic Growth Strategist",
    roleTitle: "Growth Reviewer",
    department: "content",
    responsibility:
      "Weekly organic review with proposals gated by autonomy mode.",
    trigger: { kind: "cron", schedule: "0 9 * * 1" },
    module: "content",
    executionPath: "lib/content/growth.ts",
    inngestId: "content/weekly-growth-review",
    agentNames: ["organic_growth"],
    runNow: { kind: "organic_growth", requiresBrand: true },
    moduleHref: "/content",
  },
  {
    id: "media-vision-tag",
    displayName: "Media Vision Tagger",
    roleTitle: "Asset Librarian",
    department: "content",
    responsibility: "Vision-tags media assets for search and recommendations.",
    trigger: { kind: "event", event: "brand/media.tag" },
    module: "brand",
    executionPath: "lib/media/tag.ts",
    inngestId: "brand/media-vision-tag",
    agentNames: ["media_vision_tag"],
    moduleHref: "/brand/media",
  },

  // ── Social ───────────────────────────────────────────────────────────────
  {
    id: "social-publish-due",
    displayName: "Social Publisher",
    roleTitle: "Publishing Pipeline",
    department: "social",
    responsibility:
      "Publishes due scheduled posts every 5 minutes (autonomy-gated).",
    trigger: { kind: "cron", schedule: "*/5 * * * *" },
    module: "social",
    executionPath: "lib/social/publish.ts",
    inngestId: "social/publish-due-posts",
    agentNames: [],
    moduleHref: "/social",
  },
  {
    id: "social-publish-now",
    displayName: "Instant Publisher",
    roleTitle: "Publish Now",
    department: "social",
    responsibility: "Publishes one content item immediately on request.",
    trigger: { kind: "event", event: "social/publish.requested" },
    module: "social",
    executionPath: "lib/social/publish.ts",
    inngestId: "social/publish-post-now",
    agentNames: [],
    moduleHref: "/social",
  },
  {
    id: "social-metrics",
    displayName: "Social Metrics Ingestor",
    roleTitle: "Social Analyst",
    department: "social",
    responsibility: "Daily ingest of post and follower metrics from platforms.",
    trigger: { kind: "cron", schedule: "0 6 * * *" },
    module: "social",
    executionPath: "lib/inngest/functions/social.ts",
    inngestId: "social/ingest-daily-metrics",
    agentNames: [],
    moduleHref: "/social",
  },

  // ── Advertising ──────────────────────────────────────────────────────────
  {
    id: "ads-strategist",
    displayName: "Media Planner",
    roleTitle: "Ads Strategist",
    department: "advertising",
    responsibility: "Drafts media plans with budget and channel mix.",
    trigger: { kind: "on_demand" },
    module: "ads",
    executionPath: "lib/ads/actions.ts",
    agentNames: ["ads_strategist"],
    moduleHref: "/ads/plans",
  },
  {
    id: "ads-budget-loop",
    displayName: "Budget-Only Ads Loop",
    roleTitle: "Autonomous Media Operator",
    department: "advertising",
    responsibility:
      "From the brand monthly budget, plans → paces (±20% of monthly/30) → approves/queues within org_ad_limits.",
    trigger: { kind: "cron", schedule: "0 7 * * 1" },
    module: "ads",
    executionPath: "lib/ads/budget-loop.ts",
    inngestId: "ads/budget-loop",
    agentNames: ["ads_budget_loop"],
    runNow: { kind: "ads_budget_loop", requiresBrand: true },
    moduleHref: "/brand/autonomy",
  },
  {
    id: "ads-creative",
    displayName: "Ad Creative Director",
    roleTitle: "Creative Generator",
    department: "advertising",
    responsibility: "Generates ad creative variants for a campaign.",
    trigger: { kind: "on_demand" },
    module: "ads",
    executionPath: "lib/ads/actions.ts",
    agentNames: ["ads_creative"],
    moduleHref: "/ads",
  },
  {
    id: "ads-optimisation",
    displayName: "Ads Optimiser",
    roleTitle: "Performance Optimiser",
    department: "advertising",
    responsibility:
      "Daily optimisation recommendations; auto-applies when autonomy allows.",
    trigger: { kind: "cron", schedule: "0 8 * * *" },
    module: "ads",
    executionPath: "lib/ads/optimisation.ts",
    inngestId: "ads/daily-optimisation",
    agentNames: ["ads_optimisation"],
    runNow: { kind: "ads_optimisation" },
    moduleHref: "/ads/recommendations",
  },
  {
    id: "ads-metrics-daily",
    displayName: "Ads Metrics Sync",
    roleTitle: "Ads Data Ops",
    department: "advertising",
    responsibility: "Daily sync of managed campaign metrics.",
    trigger: { kind: "cron", schedule: "0 7 * * *" },
    module: "ads",
    executionPath: "lib/ads/metrics.ts",
    inngestId: "ads/ingest-daily-metrics",
    agentNames: [],
    runNow: { kind: "ads_sync_metrics" },
    moduleHref: "/ads",
  },
  {
    id: "ads-metrics-now",
    displayName: "Ads Metrics (On Demand)",
    roleTitle: "Ads Data Ops",
    department: "advertising",
    responsibility: "On-demand sync of managed campaign metrics.",
    trigger: { kind: "event", event: "ads/metrics.sync" },
    module: "ads",
    executionPath: "lib/ads/metrics.ts",
    inngestId: "ads/sync-metrics-now",
    agentNames: [],
    runNow: { kind: "ads_sync_metrics" },
    moduleHref: "/ads",
  },

  // ── SEO ──────────────────────────────────────────────────────────────────
  {
    id: "seo-keyword-strategy",
    displayName: "Keyword Strategist",
    roleTitle: "SEO Strategist",
    department: "seo",
    responsibility: "Builds keyword strategy for an SEO project.",
    trigger: { kind: "on_demand" },
    module: "seo",
    executionPath: "lib/seo/actions.ts",
    agentNames: ["seo_keyword_strategy"],
    moduleHref: "/seo",
  },
  {
    id: "seo-content-brief",
    displayName: "Brief Writer",
    roleTitle: "SEO Brief Author",
    department: "seo",
    responsibility: "Creates content briefs from target keywords.",
    trigger: { kind: "on_demand" },
    module: "seo",
    executionPath: "lib/seo/actions.ts",
    agentNames: ["seo_content_brief"],
    moduleHref: "/seo",
  },
  {
    id: "seo-article-draft",
    displayName: "Article Drafter",
    roleTitle: "SEO Writer",
    department: "seo",
    responsibility: "Drafts long-form articles from approved briefs.",
    trigger: { kind: "on_demand" },
    module: "seo",
    executionPath: "lib/seo/actions.ts",
    agentNames: ["seo_article_draft"],
    moduleHref: "/seo",
  },
  {
    id: "seo-weekly-summary",
    displayName: "SEO Weekly Summariser",
    roleTitle: "SEO Analyst",
    department: "seo",
    responsibility: "Weekly Claude summaries of SEO performance.",
    trigger: { kind: "cron", schedule: "0 9 * * 1" },
    module: "seo",
    executionPath: "lib/seo/jobs.ts",
    inngestId: "seo/weekly-summary",
    agentNames: ["seo_weekly_summary"],
    runNow: { kind: "seo_weekly_summary" },
    moduleHref: "/seo",
  },
  {
    id: "seo-gsc-daily",
    displayName: "GSC Sync (Daily)",
    roleTitle: "Search Console Ops",
    department: "seo",
    responsibility: "Daily Google Search Console sync for all projects.",
    trigger: { kind: "cron", schedule: "0 5 * * *" },
    module: "seo",
    executionPath: "lib/inngest/functions/seo.ts",
    inngestId: "seo/sync-gsc-daily",
    agentNames: [],
    moduleHref: "/seo",
  },
  {
    id: "seo-gsc-project",
    displayName: "GSC Sync (Project)",
    roleTitle: "Search Console Ops",
    department: "seo",
    responsibility: "On-demand GSC sync for one SEO project.",
    trigger: { kind: "event", event: "seo/gsc.sync" },
    module: "seo",
    executionPath: "lib/inngest/functions/seo.ts",
    inngestId: "seo/sync-gsc-project",
    agentNames: [],
    moduleHref: "/seo",
  },
  {
    id: "seo-technical-audit",
    displayName: "Technical Auditor",
    roleTitle: "Technical SEO",
    department: "seo",
    responsibility: "Crawls and runs a technical SEO audit for a project.",
    trigger: { kind: "event", event: "seo/audit.run" },
    module: "seo",
    executionPath: "lib/inngest/functions/seo.ts",
    inngestId: "seo/run-technical-audit",
    agentNames: [],
    moduleHref: "/seo",
  },

  // ── Email ────────────────────────────────────────────────────────────────
  {
    id: "email-campaign-generate",
    displayName: "Campaign Copywriter",
    roleTitle: "Email Creative",
    department: "email",
    responsibility: "Generates campaign subject and body copy on demand.",
    trigger: { kind: "on_demand" },
    module: "email",
    executionPath: "lib/agents/email/generate.ts",
    agentNames: ["email_campaign_generate"],
    moduleHref: "/email/campaigns",
  },
  {
    id: "email-flow-strategy",
    displayName: "Flow Strategist",
    roleTitle: "Lifecycle Strategist",
    department: "email",
    responsibility: "Proposes welcome / lifecycle email flow structure.",
    trigger: { kind: "on_demand" },
    module: "email",
    executionPath: "lib/agents/email/generate.ts",
    agentNames: ["email_flow_strategy"],
    moduleHref: "/email/flows",
  },
  {
    id: "email-flow-write",
    displayName: "Flow Copywriter",
    roleTitle: "Lifecycle Writer",
    department: "email",
    responsibility: "Writes approved flow email bodies.",
    trigger: { kind: "on_demand" },
    module: "email",
    executionPath: "lib/agents/email/generate.ts",
    agentNames: ["email_flow_write"],
    moduleHref: "/email/flows",
  },
  {
    id: "email-send-campaign",
    displayName: "Campaign Sender",
    roleTitle: "Email Delivery",
    department: "email",
    responsibility: "Sends one email campaign via the connected ESP.",
    trigger: { kind: "event", event: "email/campaign.send" },
    module: "email",
    executionPath: "lib/email/send.ts",
    inngestId: "email/send-campaign",
    agentNames: [],
    moduleHref: "/email",
  },
  {
    id: "email-send-due",
    displayName: "Scheduled Sender",
    roleTitle: "Email Delivery Ops",
    department: "email",
    responsibility: "Finds and sends due scheduled campaigns every 5 minutes.",
    trigger: { kind: "cron", schedule: "*/5 * * * *" },
    module: "email",
    executionPath: "lib/inngest/functions/email.ts",
    inngestId: "email/send-due-campaigns",
    agentNames: [],
    moduleHref: "/email",
  },

  // ── CRM ──────────────────────────────────────────────────────────────────
  {
    id: "crm-pipeline-review",
    displayName: "Pipeline Reviewer",
    roleTitle: "CRM Analyst",
    department: "crm",
    responsibility: "Weekly Claude review of open pipeline by brand.",
    trigger: { kind: "cron", schedule: "0 7 * * 1" },
    module: "crm",
    executionPath: "lib/crm/pipeline-review.ts",
    inngestId: "crm/weekly-pipeline-review",
    agentNames: ["pipeline_review"],
    runNow: { kind: "pipeline_review" },
    moduleHref: "/crm",
  },
  {
    id: "crm-score-lead",
    displayName: "Lead Scorer",
    roleTitle: "Lead Qualification",
    department: "crm",
    responsibility: "Scores a contact on demand using CRM context.",
    trigger: { kind: "on_demand" },
    module: "crm",
    executionPath: "lib/agents/crm/generate.ts",
    agentNames: ["crm_score_lead"],
    moduleHref: "/crm",
  },
  {
    id: "crm-follow-up",
    displayName: "Follow-up Drafter",
    roleTitle: "Sales Enablement",
    department: "crm",
    responsibility: "Drafts follow-up emails for CRM contacts.",
    trigger: { kind: "on_demand" },
    module: "crm",
    executionPath: "lib/agents/crm/generate.ts",
    agentNames: ["crm_follow_up"],
    moduleHref: "/crm",
  },

  // ── Finance ──────────────────────────────────────────────────────────────
  {
    id: "finance-ingestion",
    displayName: "Finance Ingestor",
    roleTitle: "Finance Data Ops",
    department: "finance",
    responsibility: "Daily ingest of ad spend, AI costs, and CRM revenue.",
    trigger: { kind: "cron", schedule: "20 5 * * *" },
    module: "finance",
    executionPath: "lib/finance/ingest.ts",
    inngestId: "finance/daily-ingestion",
    agentNames: [],
    runNow: { kind: "finance_ingest" },
    moduleHref: "/finance",
  },
  {
    id: "finance-analyst",
    displayName: "Finance Analyst",
    roleTitle: "Weekly Finance Analyst",
    department: "finance",
    responsibility: "Weekly blended P&L narrative and budget vs actual.",
    trigger: { kind: "cron", schedule: "0 8 * * 1" },
    module: "finance",
    executionPath: "lib/finance/analyst.ts",
    inngestId: "finance/weekly-analyst",
    agentNames: ["finance_analyst"],
    runNow: { kind: "finance_analyst" },
    moduleHref: "/finance",
  },

  // ── Data & Analytics ─────────────────────────────────────────────────────
  {
    id: "analytics-nightly-rollup",
    displayName: "Nightly Rollup",
    roleTitle: "Analytics Ops",
    department: "analytics",
    responsibility: "Nightly GA4 sync and daily metric rollups.",
    trigger: { kind: "cron", schedule: "30 4 * * *" },
    module: "data",
    executionPath: "lib/data/rollups.ts",
    inngestId: "analytics/nightly-rollup",
    agentNames: [],
    runNow: { kind: "analytics_rollup" },
    moduleHref: "/data",
  },
  {
    id: "analytics-rollup-ondemand",
    displayName: "Rollup (On Demand)",
    roleTitle: "Analytics Ops",
    department: "analytics",
    responsibility: "On-demand GA4 sync and rollups.",
    trigger: { kind: "event", event: "analytics/rollup.run" },
    module: "data",
    executionPath: "lib/data/rollups.ts",
    inngestId: "analytics/rollup-on-demand",
    agentNames: [],
    runNow: { kind: "analytics_rollup" },
    moduleHref: "/data",
  },
  {
    id: "analytics-anomalies",
    displayName: "Anomaly Detector",
    roleTitle: "Analytics Watch",
    department: "analytics",
    responsibility: "Daily rollups plus anomaly detection with Claude context.",
    trigger: { kind: "cron", schedule: "0 6 * * *" },
    module: "data",
    executionPath: "lib/inngest/functions/analytics.ts",
    inngestId: "analytics/daily-anomalies",
    agentNames: [],
    moduleHref: "/data",
  },
  {
    id: "analytics-ask",
    displayName: "Analytics Q&A",
    roleTitle: "Data Analyst",
    department: "analytics",
    responsibility: "Answers metric questions via whitelisted query layer.",
    trigger: { kind: "on_demand" },
    module: "data",
    executionPath: "lib/agents/analytics/generate.ts",
    agentNames: ["analytics_ask"],
    moduleHref: "/data",
  },

  // ── Compliance ───────────────────────────────────────────────────────────
  {
    id: "compliance-checker",
    displayName: "Compliance Checker",
    roleTitle: "Compliance Officer",
    department: "compliance",
    responsibility:
      "Reviews publishable content against the org compliance profile.",
    trigger: { kind: "on_demand" },
    module: "compliance",
    executionPath: "lib/agents/compliance/generate.ts",
    agentNames: ["compliance_checker"],
    moduleHref: "/compliance",
  },
  {
    id: "compliance-deletions",
    displayName: "Deletion Processor",
    roleTitle: "Data Rights Ops",
    department: "compliance",
    responsibility: "Processes due organization data-deletion requests.",
    trigger: { kind: "cron", schedule: "15 3 * * *" },
    module: "compliance",
    executionPath: "lib/inngest/functions/compliance.ts",
    inngestId: "compliance/process-deletions",
    agentNames: [],
    moduleHref: "/compliance/data",
  },

  // ── Operations ───────────────────────────────────────────────────────────
  {
    id: "integration-health",
    displayName: "Integration Health Monitor",
    roleTitle: "Platform Reliability",
    department: "operations",
    responsibility: "Hourly circuit-breaker / integration health checks.",
    trigger: { kind: "cron", schedule: "15 * * * *" },
    module: "operations",
    executionPath: "lib/inngest/functions/jobs.ts",
    inngestId: "jobs/integration-health",
    agentNames: [],
    moduleHref: "/team",
  },
  {
    id: "jobs-retry",
    displayName: "Job Retrier",
    roleTitle: "Dead-letter Ops",
    department: "operations",
    responsibility: "Retries failed agent runs / resolves DLQ entries.",
    trigger: { kind: "event", event: "jobs/retry-agent-run" },
    module: "operations",
    executionPath: "lib/inngest/functions/jobs.ts",
    inngestId: "jobs/retry-agent-run",
    agentNames: [],
    moduleHref: "/team",
  },
  {
    id: "agent-run-sweeper",
    displayName: "Agent Run Sweeper",
    roleTitle: "Pipeline Ops",
    department: "operations",
    responsibility:
      "Drains queued agent_runs, heals completed-but-stuck runs, fails running >2h.",
    trigger: { kind: "cron", schedule: "*/10 * * * *" },
    module: "operations",
    executionPath: "lib/jobs/agent-run-sweeper.ts",
    inngestId: "jobs/agent-run-sweeper",
    agentNames: [],
    moduleHref: "/team",
  },
  {
    id: "automations-schedule",
    displayName: "Automation Scheduler",
    roleTitle: "Workflow Ops",
    department: "operations",
    responsibility: "Evaluates schedule-triggered automations every 5 minutes.",
    trigger: { kind: "cron", schedule: "*/5 * * * *" },
    module: "automations",
    executionPath: "lib/inngest/functions/automations.ts",
    inngestId: "automations/schedule-tick",
    agentNames: [],
    moduleHref: "/automations",
  },
  {
    id: "automations-metric",
    displayName: "Metric Automation Watch",
    roleTitle: "Workflow Ops",
    department: "operations",
    responsibility: "Daily evaluation of metric-threshold automations.",
    trigger: { kind: "cron", schedule: "10 7 * * *" },
    module: "automations",
    executionPath: "lib/inngest/functions/automations.ts",
    inngestId: "automations/metric-daily",
    agentNames: [],
    moduleHref: "/automations",
  },
  {
    id: "automations-run",
    displayName: "Automation Runner",
    roleTitle: "Workflow Executor",
    department: "operations",
    responsibility: "Runs one automation by id on request.",
    trigger: { kind: "event", event: "automation/run.requested" },
    module: "automations",
    executionPath: "lib/inngest/functions/automations.ts",
    inngestId: "automations/run-requested",
    agentNames: [],
    moduleHref: "/automations",
  },
  {
    id: "notifications-digest",
    displayName: "Digest Dispatcher",
    roleTitle: "Notification Ops",
    department: "operations",
    responsibility: "Sends daily notification digests to org members.",
    trigger: { kind: "cron", schedule: "0 8 * * *" },
    module: "settings",
    executionPath: "lib/inngest/functions/notifications.ts",
    inngestId: "notifications/daily-digest",
    agentNames: [],
    moduleHref: "/settings/notifications",
  },
  {
    id: "team-ask",
    displayName: "Ask the Team",
    roleTitle: "Cross-Department Coordinator",
    department: "operations",
    responsibility:
      "Routes user questions with live domain tools; actions go through autonomy.",
    trigger: { kind: "on_demand" },
    module: "ask",
    executionPath: "lib/team/ask/runner.ts",
    agentNames: ["team_ask"],
    moduleHref: "/ask",
  },
];

export function getAgentById(id: string): AgentRegistryEntry | undefined {
  return AGENT_REGISTRY.find((a) => a.id === id);
}

export function getAgentsByDepartment(
  department: AgentDepartment,
): AgentRegistryEntry[] {
  return AGENT_REGISTRY.filter((a) => a.department === department);
}

export function isAgentDepartment(value: string): value is AgentDepartment {
  return (AGENT_DEPARTMENTS as readonly string[]).includes(value);
}

/** All agent_names used for live agent_runs queries for an entry. */
export function agentNamesForEntry(entry: AgentRegistryEntry): string[] {
  return entry.agentNames;
}

/** Reverse lookup: agent_runs.agent_name → registry entries */
export function entriesForAgentName(agentName: string): AgentRegistryEntry[] {
  return AGENT_REGISTRY.filter((e) => e.agentNames.includes(agentName));
}
