import { jsPDF } from "jspdf";

import { createAdminClient } from "@/lib/supabase/admin";
import type { Report, ReportContent } from "@/lib/types/reviews";
import { REPORT_TYPE_LABELS } from "@/lib/types/reviews";

function money(n: number) {
  return `£${n.toLocaleString(undefined, { maximumFractionDigits: 2 })}`;
}

export function buildReportPdfBuffer(params: {
  report: Pick<Report, "title" | "type" | "period_start" | "period_end">;
  content: ReportContent;
}): ArrayBuffer {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const primary = params.content.branding?.primary_color ?? "#0F6F68";
  const brand = params.content.branding?.brand_name ?? "Brand";
  const margin = 48;
  const maxWidth = 500;
  let y = 48;

  const ensureSpace = (need: number) => {
    if (y + need > 780) {
      doc.addPage();
      y = 48;
    }
  };

  const write = (text: string, opts?: { size?: number; color?: string; bold?: boolean }) => {
    ensureSpace(18);
    doc.setFontSize(opts?.size ?? 11);
    doc.setTextColor(opts?.color ?? "#111111");
    doc.setFont("helvetica", opts?.bold ? "bold" : "normal");
    const lines = doc.splitTextToSize(text, maxWidth);
    for (const line of lines) {
      ensureSpace(14);
      doc.text(line, margin, y);
      y += opts?.size && opts.size > 14 ? 18 : 14;
    }
  };

  // Header bar
  doc.setFillColor(primary);
  doc.rect(0, 0, 595, 36, "F");
  doc.setTextColor("#ffffff");
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(`${brand} · ${REPORT_TYPE_LABELS[params.report.type]} report`, margin, 22);
  y = 56;

  write(params.report.title, { size: 18, bold: true, color: primary });
  write(
    `Period ${params.report.period_start} → ${params.report.period_end}`,
    { size: 10, color: "#666666" },
  );
  y += 8;
  write(params.content.summary, { size: 11 });
  y += 10;

  write("Headline numbers", { size: 14, bold: true, color: primary });
  for (const h of params.content.headline_numbers ?? []) {
    const delta =
      h.delta_pct == null ? "n/a" : `${h.delta_pct > 0 ? "+" : ""}${h.delta_pct}%`;
    const val =
      h.unit === "£" ? money(h.value) : `${h.value}${h.unit ? ` ${h.unit}` : ""}`;
    write(`• ${h.label}: ${val} (Δ ${delta}${h.target != null ? `, target ${h.target}` : ""})`);
  }
  y += 8;

  write("Channel breakdown", { size: 14, bold: true, color: primary });
  for (const ch of params.content.channels ?? []) {
    write(ch.channel, { bold: true });
    write(ch.commentary);
    write(`Metrics: ${JSON.stringify(ch.metrics)}`, { size: 9, color: "#555555" });
    y += 4;
  }

  if ((params.content.campaigns ?? []).length) {
    y += 4;
    write("Campaign performance", { size: 14, bold: true, color: primary });
    for (const c of params.content.campaigns) {
      write(
        `${c.name} [${c.status}] — spent £${(c.spent_pence / 100).toFixed(0)} / £${(c.budget_pence / 100).toFixed(0)}`,
        { bold: true },
      );
      write(c.commentary);
    }
  }

  y += 6;
  write("Insights", { size: 14, bold: true, color: primary });
  for (const i of params.content.insights ?? []) write(`• ${i}`);

  y += 6;
  write("Recommendations", { size: 14, bold: true, color: primary });
  for (const r of params.content.recommendations ?? []) write(`• ${r}`);

  if (params.content.plan_retrospective) {
    y += 6;
    write("Plan retrospective", { size: 14, bold: true, color: primary });
    write("What worked:", { bold: true });
    for (const x of params.content.plan_retrospective.what_worked) write(`• ${x}`);
    write("What missed:", { bold: true });
    for (const x of params.content.plan_retrospective.what_missed) write(`• ${x}`);
    write("Lessons:", { bold: true });
    for (const x of params.content.plan_retrospective.lessons) write(`• ${x}`);
  }

  if ((params.content.next_quarter_proposals ?? []).length) {
    y += 6;
    write("Next quarter proposals", { size: 14, bold: true, color: primary });
    for (const x of params.content.next_quarter_proposals ?? []) write(`• ${x}`);
  }

  y += 16;
  write("Generated by Simba AI", { size: 9, color: "#5A6E6B" });

  return doc.output("arraybuffer");
}

export async function uploadReportPdf(params: {
  organizationId: string;
  reportId: string;
  buffer: ArrayBuffer;
}): Promise<string | null> {
  const supabase = createAdminClient();
  const path = `${params.organizationId}/${params.reportId}.pdf`;
  const { error } = await supabase.storage.from("reports").upload(path, params.buffer, {
    contentType: "application/pdf",
    upsert: true,
  });
  if (error) {
    console.error("PDF upload failed", error.message);
    return null;
  }
  const { data } = supabase.storage.from("reports").getPublicUrl(path);
  return data.publicUrl;
}
